[package]
name = "bevy_retro_macros"
version = "0.1.0"
authors = ["Zicklag <zicklag@katharostech.com>"]
edition = "2018"

[lib]
proc_macro = true

[dependencies]
quote = "1.0.9"
proc-macro2 = "1.0.24"
syn = "1.0.60"
